version: '3.7'

services:

  rabbitmq1:
    image: webitel/rabbitmq
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=webitel
      - RABBITMQ_DEFAULT_PASS=webitel
      - RABBITMQ_ERLANG_COOKIE="123-SECRET-KEY-987"
    networks:
      - wtel_vlan
    volumes:
      - data1:/var/lib/rabbitmq
    deploy:
      mode: global
      placement:
        constraints: [node.labels.rabbitmq1 == true]

  rabbitmq2:
    image: webitel/rabbitmq
    hostname: rabbitmq2
    environment:
      - RABBITMQ_DEFAULT_USER=webitel
      - RABBITMQ_DEFAULT_PASS=webitel
      - RABBITMQ_ERLANG_COOKIE="123-SECRET-KEY-987"
    networks:
      - wtel_vlan
    volumes:
      - data2:/var/lib/rabbitmq
    deploy:
      mode: global
      placement:
        constraints: [node.labels.rabbitmq2 == true]

  rabbit:
    image: webitel/haproxy-for-rabbitmq
    networks:
      - wnet_macvlan_swarm
      - wtel_vlan
    deploy:
      mode: global

networks:
  wtel_vlan:
    external: true
  wnet_macvlan_swarm:
    external: true

volumes:
  data1:
  data2:
