version: '3.2'

services:
  consul:
    image: consul:latest
#    ports:
#      - 8500:8500
    networks:
      wtel_vlan:
        aliases:
          - consul.cluster
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - "CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true, \"acl_default_policy\":\"allow\", \"acl_down_policy\":\"extend-cache\", \"server\":true }"
    command: ["agent", "-server", "-bootstrap", "-client=0.0.0.0", "-retry-join=consul.server", "-retry-join=consul.agent", "-datacenter=swarm", "-domain=wtel", "-ui"]
    deploy:
      mode: replicated
      replicas: 1

  server:
    image: consul:latest
    networks:
      wtel_vlan:
        aliases:
          - consul.server
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - "CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true, \"acl_default_policy\":\"allow\", \"acl_down_policy\":\"extend-cache\", \"server\":true }"
    command: ["agent", "-client=0.0.0.0", "-retry-join=consul.cluster", "-retry-join=consul.agent",  "-datacenter=swarm", "-domain=wtel"]
    deploy:
      mode: replicated
      replicas: 1

  agent:
    image: consul:latest
    networks:
      wtel_vlan:
        aliases:
          - consul.agent
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - "CONSUL_LOCAL_CONFIG={\"leave_on_terminate\": true, \"acl_default_policy\":\"allow\", \"acl_down_policy\":\"extend-cache\", \"server\":true }"
    command: ["agent", "-client=0.0.0.0", "-retry-join=consul.server", "-retry-join=consul.cluster",  "-datacenter=swarm", "-domain=wtel"]
    deploy:
      mode: replicated
      replicas: 1

networks:
  wtel_vlan:
    external: true
