---
version: '3.7'

services:
  opensips:
    hostname: 'opensips'
    image: webitel/opensips:3.0
    command: ["/opensips/sbin/opensips", "-DD"]
    environment:
      - CONSUL=$CONSUL
    networks:
      - wnet_macvlan_swarm
      - wnet
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    volumes:
      - web_config:/config
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
  engine:
    image: webitel/engine:latest
    command: ["-consul", "$CONSUL:8500"]
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    networks:
      - wnet
  acr:
    image: webitel/acr:latest
    ports:
      - 10030:10030
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    networks:
      - wnet
  sip-uac:
    image: webitel/webitel:latest
    command: ["uac", "--opensips-sip-address=dev.webitel.com", "--opensips-mi-address=http://opensips:8000/mi"]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    networks:
      - wnet
  directory:
    image: webitel/webitel:latest
    command: ["dsa"]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    volumes:
      - run_data:/usr/local/webitel/run
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    networks:
      - wnet
  app:
    image: webitel/webitel:latest
    command: ["app"]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    volumes:
      - run_data:/usr/local/webitel/run
    extra_hosts:
      - rabbit:$AMQP
      - postgres:$PGSQL
    networks:
      - wnet
  httpapi:
    hostname: 'httpapi'
    image: webitel/webitel:latest
    command: ["api", "--address=:80"]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    volumes:
      - run_data:/usr/local/webitel/run
    extra_hosts:
      - rabbit:$AMQP
    networks:
      - wnet
  httpapi-docs:
    image: webitel/swagger-api-docs
    networks:
      - wnet
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  frontend:
    image: webitel/web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - URL=webitel.com
      - SUBDOMAINS=dev
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - web_config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - wnet
    deploy:
      mode: global

networks:
  wnet:
    driver: overlay
    attachable: true
  wnet_macvlan_swarm:
    external: true

volumes:
  run_data:
  web_config:
