version: '3.7'

services:
  elastic:
    image: amazon/opendistro-for-elasticsearch:1.3.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - cluster.name=odfe-cluster
      - node.name={{.Node.Hostname}}
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=$ODFEHOSTS
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - odfe-data:/usr/share/elasticsearch/data
    networks:
      - wtel_vlan
    deploy:
      mode: global
      placement:
        constraints: [node.labels.elastic == true]
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 1024M

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.3.0
    hostname: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://elastic:9200
      ELASTICSEARCH_HOSTS: https://elastic:9200
    networks:
      - wtel_vlan
    deploy:
      mode: replicated
      replicas: 1

volumes:
  odfe-data:

networks:
  wtel_vlan:
    external: true
