version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: ["-H", "tcp://tasks.agent:9001", "--tlsskipverify", "--logo", "https://avatars3.githubusercontent.com/u/9943327", "-t", "https://raw.githubusercontent.com/webitel/webitel/master/templates.json"]
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  consul:
    image: consul:latest
    hostname: "{{.Node.Hostname}}"
    volumes:
      - consul_data:/consul/data
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600/udp
    networks:
      - agent_network
    command: ["consul", "agent", "-dev", "-datacenter=swarm", "-domain=wtel", "-client=0.0.0.0", "-log-level=warn", "-ui"]
    #command: [ "agent", "-server", "-bootstrap-expect=3", "-retry-max=3", "-retry-interval=10s", "-datacenter=swarm", "-domain=wtel", "-join=consul", "-retry-join=consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
  consul_data:
