version: '3.2'

services:
  consul:
    image: consul:latest
    hostname: consul
    volumes:
      - consul_data:/consul/data
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600/udp
    networks:
      - wtel_lan
    command: ["consul", "-server", "-node=consul", "-datacenter=swarm", "-domain=wtel", "-bootstrap-expect=1", "-client=0.0.0.0", "-log-level=warn", "-ui"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  consul:
    image: consul:latest
    hostname: consul
    volumes:
      - consul_client_data:/consul/data
    networks:
      - wtel_lan
    command: ["consul", "agent", "-dev", "-datacenter=swarm", "-domain=wtel", "-retry-max=3", "-retry-interval=10s" "-join=consul", "-retry-join=consul", "-log-level=warn"]
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  wtel_vlan:
    external: true

volumes:
  consul_data:
  consul_client_data:
