---
version: '3.7'

services:
  opensips:
    hostname: 'opensips'
    image: webitel/opensips:3.0
    command: ["/opensips/sbin/opensips", "-DD"]
    environment:
      - CONSUL=consul
    networks:
      - wnet_macvlan_swarm
      - wtel_vlan
    volumes:
      - web_config:/config
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
  engine:
    image: webitel/engine:latest
    command: ["-consul", "consul:8500"]
    networks:
      - wtel_vlan
  acr:
    image: webitel/acr:latest
    ports:
      - 10030:10030
    networks:
      - wtel_vlan
  sip-uac:
    image: webitel/webitel:latest
    command: ["uac", "--opensips-sip-address=$SIPHOST", "--opensips-mi-address=http://opensips:8000/mi"]
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - wtel_vlan
  directory:
    image: webitel/webitel:latest
    command: ["dsa"]
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    volumes:
      - run_data:/usr/local/webitel/run
    networks:
      - wtel_vlan
  app:
    image: webitel/webitel:latest
    command: ["app"]
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    volumes:
      - run_data:/usr/local/webitel/run
    networks:
      - wtel_vlan
  httpapi:
    hostname: 'httpapi'
    image: webitel/webitel:latest
    command: ["api", "--address=:80"]
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    volumes:
      - run_data:/usr/local/webitel/run
    networks:
      - wtel_vlan
  httpapi-docs:
    image: webitel/swagger-api-docs
    networks:
      - wtel_vlan
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  frontend:
    image: webitel/web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - URL=webitel.com
      - SUBDOMAINS=dev
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - web_config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - wtel_vlan
    deploy:
      mode: global

networks:
  wnet_macvlan_swarm:
    external: true
  wtel_vlan:
    external: true

volumes:
  run_data:
  web_config:
