---
version: '3.7'

services:
  rabbit:
    hostname: 'rabbit'
    image: webitel/amqp
    environment:
      - RABBITMQ_DEFAULT_USER=webitel
      - RABBITMQ_DEFAULT_PASS=webitel
      - RABBITMQ_NODENAME=webitel@rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  postgres:
    hostname: 'postgres'
    image: webitel/postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  opensips:
    hostname: 'opensips'
    image: webitel/opensips:3.0
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  sbc:
    hostname: 'sbc'
    image: webitel/freeswitch:1.8.7
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  fs1:
    hostname: 'fs1'
    image: webitel/freeswitch:1.8.7
    environment:
      - CONSUL=$CONSUL
    volumes:
      - fs_sounds:/sounds
      - fs_recordings:/recordings
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  wnet:
    driver: overlay
    attachable: true
  wnet_macvlan_swarm:
    external: true

volumes:
  fs_sounds:
  fs_recordings:
  rabbitmq_data:
  postgres_data:
  consul_data:
