version: '3.7'

services:

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.3.0
    hostname: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://elastic:9200
      ELASTICSEARCH_HOSTS: https://elastic:9200
    networks:
      - wtel_vlan
    deploy:
      mode: replicated
      replicas: 1

networks:
  wtel_vlan:
    external: true
