---
version: '3.7'

services:
  rabbit:
    hostname: 'rabbit'
    image: webitel/amqp
    environment:
      - RABBITMQ_DEFAULT_USER=webitel
      - RABBITMQ_DEFAULT_PASS=webitel
      - RABBITMQ_NODENAME=webitel@rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  postgres:
    hostname: 'postgres'
    image: webitel/postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  opensips:
    hostname: 'opensips'
    image: webitel/opensips:3.0
    environment:
      - CONSUL=$CONSUL
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  sbc:
    hostname: 'sbc'
    image: webitel/freeswitch:1.8.7
    environment:
      - SBC=true
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  fs1:
    hostname: 'fs1'
    image: webitel/freeswitch:1.8.7
    environment:
      - CONSUL=$CONSUL
    volumes:
      - fs_sounds:/sounds
      - fs_recordings:/recordings
    networks:
      - wnet_macvlan_swarm
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  directory:
    image: webitel/webitel
    command: ["dsa", "--db-dsn=\"host=postgres port=5432 dbname=webitel sslmode=disable user=opensips password=webitel\""]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    volumes:
      - run_data:/usr/local/webitel/run
    networks:
      - wnet
  httpapi:
    hostname: 'httpapi'
    image: webitel/webitel
    command: ["api", "--address=:80"]
    environment:
      - MICRO_REGISTRY_ADDRESS=$CONSUL
    volumes:
      - run_data:/usr/local/webitel/run
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  client:
    image: webitel/client
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  wnet:
    driver: overlay
    attachable: true
  wnet_macvlan_swarm:
    external: true

volumes:
  run_data:
  fs_sounds:
  fs_recordings:
  rabbitmq_data:
  postgres_data:
